// gen-entry.mjs — write the SSR entry that prerenders each section of a site.
//
// Usage: node gen-entry.mjs <site-dir> <out-file>
//
// Reads src/App.tsx, which by convention only composes sections, and emits a
// tiny entry that renders each section on its own with renderToStaticMarkup.
// Rendering sections separately (rather than <App/> as a whole) keeps the
// section boundaries — one file per section is what the WordPress theme needs.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'

const [siteDir, outFile] = process.argv.slice(2)
if (!siteDir || !outFile) {
  console.error('usage: gen-entry.mjs <site-dir> <out-file>')
  process.exit(1)
}

const appPath = join(siteDir, 'src', 'App.tsx')
let app
try {
  app = readFileSync(appPath, 'utf8')
} catch {
  console.error(`error: cannot read ${appPath}`)
  process.exit(1)
}

// Which components does App import, and from where?
const sources = new Map()
for (const m of app.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/g)) {
  for (const raw of m[1].split(',')) {
    const name = raw.trim().split(/\s+as\s+/).pop().trim()
    if (/^[A-Z]/.test(name)) sources.set(name, m[2])
  }
}

// In which order does it render them? Self-closing capitalised tags only —
// that is the house shape (<Hero /><Features />…), and anything with props or
// children is not a plain section.
const seen = new Set()
const sections = []
for (const m of app.matchAll(/<([A-Z][A-Za-z0-9_]*)\s*\/>/g)) {
  const name = m[1]
  if (!sources.has(name) || seen.has(name)) continue
  seen.add(name)
  sections.push({ name, source: sources.get(name) })
}

if (sections.length === 0) {
  console.error(
    'error: no sections found in src/App.tsx — App must import and render ' +
      'self-closing section components (see CLAUDE.md "Design direction")',
  )
  process.exit(1)
}

const entry = `// Generated by scripts/wp/gen-entry.mjs — do not edit, do not commit.
import { renderToStaticMarkup } from 'react-dom/server'
import { writeFileSync } from 'node:fs'
${sections.map((s) => `import { ${s.name} } from '${s.source}'`).join('\n')}

const sections = [
${sections.map((s) => `  { name: '${s.name}', html: renderToStaticMarkup(<${s.name} />) },`).join('\n')}
]

writeFileSync(process.argv[2], JSON.stringify(sections, null, 2))
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, entry)
console.log(`sections: ${sections.map((s) => s.name).join(', ')}`)
